
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="MIT" #mandatory
issueTrackerURL="https://github.com/Da-Technomancer/Essentials" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="essentials" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Essentials" #mandatory
# updateJSONURL="http://myurl.me/" #optional
# displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional
credits='''
Developers & Maintainers: Technomancer.
Artists: 5284973.
Translators: XuyuEre, Луксиния Гримхольд, scikirbypoke.
Misc Contributors: Bord Listian.''' #optional
authors="Technomancer" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds utility blocks and light-weight features that expand vanilla-style automation.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.essentials]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[40,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.essentials]]
modId="minecraft"
mandatory=true
versionRange="[1.19,]"
ordering="NONE"
side="BOTH"