modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory
issueTrackerURL="https://github.com/Da-Technomancer/Essentials" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="essentials" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Essentials" #mandatory
# updateJSONURL="http://myurl.me/" #optional
# displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional
credits='''Many textures created by 5284973. Translations by XuyuEre.''' #optional
authors="Da_Technomancer" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds several utility blocks that expand vanilla-style automation
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.essentials]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.essentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"